### ISSUE TITLE
Flickering when switching profile if Eye Adaption is enabled

### ISSUE THREAD

**Issue by TJHeuvel** [Unity-Technologies/PostProcessing#198]
##### What happened?
In our implementation we often switch profiles, however this causes issues when Eye Adaption is enabled. It flickers every time you switch profiles:

https://streamable.com/fz375

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 5.5, Win10, Standalone win/mac/linux, PS4 X1

**Comment by Chman** [comment]
That's because it's trying to adapt from a black frame. Calling `ResetTemporalEffects()` on the `PostProcessingBehaviour` after you switch profiles should fix it.

**Comment by TJHeuvel** [comment]
This does not solve our issues.

**Comment by Kink3d** [comment]
Hi,

Sorry for the incredibly late reply. Are you sure this doesnt fix your issue? Can you try latest V1?

I just tested this and it works (although I believe some fixes may have been made in this area)

```
using UnityEngine;
using UnityEngine.PostProcessing;

public class EyeAdaptationSwitch : MonoBehaviour {

    public PostProcessingProfile[] profiles;
    public bool switchProfile = false;

    PostProcessingBehaviour behaviour;
    int currentProfile;

	void Start ()
    {
        behaviour = GetComponent<PostProcessingBehaviour>();
	}

	void Update ()
    {
		if(behaviour)
        {
            if(switchProfile)
            {
                switchProfile = false;
                if(currentProfile < profiles.Length - 1)
                {
                    currentProfile++;
                    behaviour.profile = profiles[currentProfile];
                }
                else
                {
                    currentProfile = 0;
                    behaviour.profile = profiles[currentProfile];
                }
            }
            behaviour.ResetTemporalEffects(); // This fixes the issue
        }
	}
}
```

**Comment by TJHeuvel** [comment]
It seems like it is still bugged using the latest version. We instantiate a new profile, that seems to be the problem.

Please find a test project here: https://we.tl/2LUybOIsic

Essentially what we are doing is:

`behaviour.profile = Instantiate(behaviour.profile);`

This, with eye adaption enabled, will break it.
