### ISSUE TITLE
Camera render broken when editor is in 2D mode and MSAA is turned off

### ISSUE THREAD

**Issue by Elringus** [Unity-Technologies/PostProcessing#226]
##### What happened?
When editor is in 2D mode (Project Settings -> Editor -> Default Behavior Mode -> 2D) and MSAA is turned of in Quality Settings (or "Allow MSAA" is unchecked on rendering camera) camera fills with solid color, not rendering anything, except UI.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Reproduced on Unity 5.6.2p4 and 2017.1.0f3 (Windows 10), standalone and WebGL platforms.

**Comment by Chman** [comment]
Should be fixed in 8ebad26.

**Comment by Elringus** [comment]
Thanks for the fix, but it seems something is still wrong with the HDR in 2D editor mode. When it’s switched to 2D bloom ignores HDR colors (or maybe they’re just clamped to LDR). 

Here, I’ve recorded it: https://youtu.be/F9DFgFaZc3s
Repro project used in the video: https://github.com/Elringus/SpriteGlow

**Comment by Chman** [comment]
Thanks for the video & repro, that's very helpful. It seems that when "2D behavior" is enabled the camera target will always use a 8bit render target format even if HDR is enabled. I'll pass this to the 2D team and will let you know once I know more.

**Comment by Kink3d** [comment]
This bug is now with the 2D team.

Here is the Isse Tracker link so you can keep an eye on it: https://issuetracker.unity3d.com/issues/setting-default-behavior-mode-to-2d-breaks-hdr-rendering

Thanks for reporting!
