### ISSUE TITLE
DoF doesn't handle alpha cutout very well

### ISSUE THREAD

**Issue by robertcupisz** [Unity-Technologies/PostProcessing#40]
![dofcutouttest](https://cloud.githubusercontent.com/assets/6276154/21262878/f361f98a-c393-11e6-9fa7-386f5fa19914.PNG)

DoF doesn't handle alpha cutout geometry very well. Looks like an upsampling issue? The edges of the of the in-focus cutouts pick up sharp instead of blurred background.

Please ping me about the repro project. I have it ready, but can't post it publicly.

**Comment by Kink3d** [comment]
Confirmed fixed in @keijiro 's branch, will get a PR.

**Comment by robertcupisz** [comment]
![image](https://cloud.githubusercontent.com/assets/6276154/21890740/67dd6c5e-d8cf-11e6-95f7-f48c1458ca6b.png)

Looks like the artifacts aren't completely gone. Can it still be improved?

Also there's some visible lower-res aliasing, e.g. visible on the dark vertical branch in the center - an upsample filter issue?

**Comment by keijiro** [comment]
I've pushed a possible fix for this issue to my fork of the stack.

https://github.com/keijiro/PostProcessing/commit/db1c48ffb871a4e1e7361d10243b11c82e03f8b1

It hasn't been merged to the master branch because it's still a bit experimental. You can get the fix from the dof-coc-resample branch in my fork.

https://github.com/keijiro/PostProcessing/tree/dof-coc-resample

Could you verify if this fix works for your use-case? I'll consider merging it to master based on feedback and further performance profiling.

**Comment by robertcupisz** [comment]
Thanks a lot for your time, Keijiro.

Enabling CoC resampling makes the test scene work nicely:
![a4](https://cloud.githubusercontent.com/assets/6276154/22426623/43a0608c-e700-11e6-8d9b-97665bbff0f7.PNG)

I'll try out the fix in our real scene and let you know about any potential issues, but this scene was the hardest case.

On a somewhat related note, DoF still introduces a dark halo around objects in focus. I'm mentioning it here, because enabling CoC resample makes the effect more pronounced since the silhouette is suddenly much sharper. I will update https://github.com/Unity-Technologies/PostProcessing/issues/26 with new images and test scene in a moment.

**Comment by robertcupisz** [comment]
Looks like the CoC resampling doesn't play nice with eye adaptation.

In the example project: if you crank up exposure compensation and enable CoC resampling, ec gets ignored on the out of focus background.

**Comment by robertcupisz** [comment]
@keijiro After some more testing, it looks like CoC resampling doesn't play nice with TAA either.

To be more specific, we're doing auto focus, and with CoC resampling enabled, TAA enabled AND focus distance changing (i.e. quick CoC size change) the result is heavy black outlines/glitches, like in this video:
https://www.dropbox.com/s/l5t94o4w6l4kcd2/CoCResampling%20vs%20TAA%20and%20auto%20focus%20-%20glitches.mp4?dl=0

**Comment by keijiro** [comment]
I fixed the TAA issue and the eye adaptation issue in dof-coc-resample branch. https://github.com/keijiro/PostProcessing/commit/47e4c07f07dece428792197a557e75be6be533cf

**Comment by robertcupisz** [comment]
@keijiro Thanks!

I've tested https://github.com/keijiro/PostProcessing/commit/47e4c07f07dece428792197a557e75be6be533cf

The eye adaptation issue and black TAA ghosting is indeed gone - nice!

We have two new issues though. I reproduced them in the simple project, but in two separate scenes.
https://www.dropbox.com/s/uox0cigdps38tui/DoFCutoutTest%20-%20Edges%20and%20NaN.zip?dl=1

1. Scene: DoFCutoutTest
With TAA disabled looks great! But with TAA enabled, the original issue from this thread is still visible, i.e. the edges are jagged and show unblurred background in places (although less than they used to). This is much more jarring with color grading, since in our case those individual pixels get very different colors than the blurred background around - but it's still visible here:

![dofedges](https://cloud.githubusercontent.com/assets/6276154/22594954/a45216b4-ea25-11e6-976b-975559d8e8be.PNG)


2. Scene: DoFCutoutTest - NaN (press play, the camera will animate)
This is a new issue - NaN blobs started appearing. In this project I could only reproduce it with TAA enabled, but in our project it reproduced also with TAA disabled (and only DoF, no other effects).

![dofnan](https://cloud.githubusercontent.com/assets/6276154/22595023/fd2fa86e-ea25-11e6-976a-aaa0f9e5e695.PNG)

**Comment by keijiro** [comment]
Thanks for the further reports. I've only fixed the NaN issue. Now I'm tackling the TAA problem.

**Comment by keijiro** [comment]
Fixed in 42319c1b13b4106affb358f691da0c2f56f9d2d6

**Comment by Kink3d** [comment]
Confirmed fixed in reproduction project.

**Comment by robertcupisz** [comment]
The artifacts are mostly gone in the test project, but still present in our scene in more tricky cases. Since the incorrectly unblurred pixels are pulled down to ldr, they react differently to the grading than the neighbouring blurred white sky pixels, and they appear as cyan - which makes the artifact even more pronounced.

![dof](https://cloud.githubusercontent.com/assets/6276154/25389390/c017578e-29d0-11e7-83bb-f3ea4ba0a176.jpg)

Is it something you think can still be improved without resorting to calculating dof at full resolution?
