### ISSUE TITLE
Null references exceptions in AmbientOcclusion.IsEnabledAndSupported on prefab

### ISSUE THREAD

**Issue by dan-goyette** [Unity-Technologies/PostProcessing#467]
##### What happened?

Short Version: NullReferenceExceptions in all scenes that contain a prefab that has Post-processing stack components on it, except for the scene in which the components were added to the prefab.

I've uploaded a trivial sample project here: https://drive.google.com/open?id=1XWswyPTriC0IQNtxCBa8UHo3VjZZ_mJ_

The project contains a "Player" prefab, which has a camera, PPS Volume, and PPS Layer on it. I've added this prefab to the two scenes in my project, Scene1 and Scene2. I originally added the PPS components to the "Player" prefab while I was in Scene1. When I then switch to Scene2, I get NullReferenceExceptions in the Editor, and constantly while in play mode:

`
NullReferenceException: Object reference not set to an instance of an object
UnityEngine.Rendering.PostProcessing.AmbientOcclusion.IsEnabledAndSupported (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Assets/PostProcessing/Runtime/Effects/AmbientOcclusion.cs:90)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.SetLegacyCameraFlags (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Assets/PostProcessing/Runtime/PostProcessLayer.cs:513)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.SetupContext (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Assets/PostProcessing/Runtime/PostProcessLayer.cs:568)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.BuildCommandBuffers () (at Assets/PostProcessing/Runtime/PostProcessLayer.cs:324)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.OnPreCull () (at Assets/PostProcessing/Runtime/PostProcessLayer.cs:295)
`

The code keeps trying to access context.resources.shaders.multiScaleAO, but context.resources is null.

The only way to stop these NullReferenceExceptions is to remove the PPS components and add them back in again.

To reproduce this in the sample project I've attached, it should be enough to go to Scene2, remove the "Player" from the scene, and then drag the "Player" prefab back into the scene.

##### Post-processing stack version (v1, v2)?

Post-processing Stack V2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Windows 10
Targetting Windows x86_64
Unity 2017.3.0p2
Linear color space, deferred rendering

**Comment by Chman** [comment]
This should already be [fixed on master](https://github.com/Unity-Technologies/PostProcessing/blob/v2/PostProcessing/Runtime/Effects/AmbientOcclusion.cs#L88). Are you running beta5 or a previous master snapshot?

**Comment by dan-goyette** [comment]
It's whatever was in the code base when I downloaded a zip version of the 'v2' branch on February 15, 2018 at 12:24 PM, and it's still happening when I get the download 'v2' branch as of today.

The issue, though, isn't that `context` is null, but that `context.resources` is null. I tried adding a few null checks for context.resources being null, but this just keeps causing new errors, as there are a lot of dependencies on context.resources. 

What I'm puzzled by with this error is that in some scenes, things load fine. But if I put my prefab in a new scene, I will get this error until I remove and re-add the post-processing stack components to my prefab, and then Apply the prefab again. In the sample project I referenced, you can get this error very easily by doing the following:

- Add a new Scene to the project, and open it.
- Drag the "Player" prefab into the scene.
- You should see the error in the console immediately upon adding the "Player", and you'll see it repeatedly if you enter Play Mode.

I'm questioning whether I've just configured the post-processing stack components incorrectly, since it seems like this should be a rampant issue for many users otherwise.

**Comment by dan-goyette** [comment]
Just a but more on this, if it helps, as I was trying to devise a workaround.

I hacked the Post Process Layer class and editor to make m_Resources public, and to show it in the inspector. When I add a new Post Process Layer component to my object, it is created with resources assigned:

![image](https://user-images.githubusercontent.com/12823055/36346240-0120b84e-13f8-11e8-91f5-21eab5805b31.png)

However, if I then change some property of the Post Process Layer, such as toggling "Exclude Skybox", and "Apply" my prefab, the Resources value is cleared out, and I am unable to set a new value for it. This is only apparent when reloading the scene, or deleting the prefab from the scene and adding it back:

![image](https://user-images.githubusercontent.com/12823055/36346261-6414de94-13f8-11e8-9376-6ee33a0b3154.png)

Things seem relatively stable for a while as long as I don't adjust the settings of the Post Process Layer. But any time I edit the Post Process layer, then Apply the prefab, it seems to lose its association to Resources.

**Comment by AubreyF** [comment]
I'm experiencing the same issue, and pulling the latest build from Master 15 minutes ago did not resolve. I'm currently working around this issue by recreating each PostProcess layer on level load via scripting as necessary.

**Comment by Chman** [comment]
I finally got some time to look at your repro (thanks for providing one by the way). Your prefab is broken, something probably went wrong with its meta file. Switching to debug view in the inspector you can see the `Resources` field is null:

![image](https://user-images.githubusercontent.com/849090/36354230-6a7414b0-14d1-11e8-8a36-0e7b440ce708.png)

Put it back there, recreate the prefab or reset the post process layer component and it'll be fixed. I played around with postfx in prefabs, creating, deleting, breaking instances, manipulating them and I couldn't find anything out of the ordinary.

**Comment by AubreyF** [comment]
@Chman This issue is 100% reproducible for me. Steps:

1) Create a prefab which contains a child camera with an associated PostProcessLayer.
2) Instantiate prefab at runtime.
3) Even if the prefab's Resources link is valid, the instantiated version will have missing resources.

**Comment by Chman** [comment]
Hmmm if that's the case (haven't tried it yet) it would mean there's an issue with prefabs meta data when they get instantiated via scripting. I know that default references only work in the editor (as in, if you add a component via scripting you'll have to populate the default references yourself), maybe prefabs don't bake default references in either, I can see how that could be problematic.

I'll investigate as well.

**Comment by dan-goyette** [comment]
Thanks for investigating, Chman. If the prefab is breaking, it's easy to reproduce in a new project. This is all I need to do to get the exception:

- Create a new Unity project, and drop PostProcessing into it.
- Create an empty game object in the default scene, and add a Post Process Layer to it.
- Drag the game object into a project directory to turn the object into a prefab.
- Make a change to basically any property on the game object (it doesn't need to be the post process layer. For example, I changed the camera's near clipping value) then click Apply.
- Remove the game object from the scene, and then drag the prefab into the scene again.

You should immediately see the exception. It seems that hitting Apply to the prefab clears the Resources value of the Post Process Layer.

**Comment by dan-goyette** [comment]
You might have already noticed this, but it looks like this behavior was introduced in "Make sure that PostProcessStrippingConfig asset always exists" (https://github.com/Unity-Technologies/PostProcessing/commit/737c744557f2fc954f19d7955c4a0859b76eafa5). If I revert back to the previous commit "Merge pull request #455 from Unity-Technologies/build/automation"
 (https://github.com/Unity-Technologies/PostProcessing/commit/c0da41243dbf7a596f744808cbba591b4836e25a) I no longer get the error.

**Comment by demonixis** [comment]
Hi,

I've this error too. My workarround is to edit the file PostProcessLayer and add that line

```csharp
public void Init(PostProcessResources resources)
{
    if (m_Resources != null)
        return;
```

Then in my player script:

```csharp
var layer = GetComponentInChildren<PostProcessLayer>();
layer.Init(m_PostProcessResources);
```

I'm not very proud of that, I hope we can get this issue fixed soon.

**Comment by Chman** [comment]
Latest commit should fix this issue. Please report back if it doesn't.

**Comment by demonixis** [comment]
Hi,

I doesn't fix the issue, I still have to manually edit the post Processing layer.

**Comment by Chman** [comment]
It does fix it (it doesn't reproduce here after the latest commit, using the same steps as previously described) but an unfortunate side effect is that the previously created `PostProcessLayer` instances (before patch) will have to be recreated after the "fixed" version is imported.

**Comment by demonixis** [comment]
You're right! It's fixed when I recreate it. Thanks :)

**Comment by dan-goyette** [comment]
Looks good. Thanks for the quick fix.

**Comment by jonburesh** [comment]
Bump, having this issue in the newest version. Running 2018.1.6, installed with the package manager. All newly created PostProcessLayer are missing the PostProcessResources

**Comment by ltetzlaff** [comment]
I also had it this afternoon, after adding it as a git submodule.

The only solution that worked for me was removing the script files, let it compile and `git reset --hard` the submodule, so I'd guess removing and readding the files should usually do the trick. Right-click -> reimport was not enough somehow.

**Comment by thomasgauthier** [comment]
I am also experiencing this issue in Unity 2018.2.6 with newest source for the Post Processing Stack (tried both Package Manager and Github version).

**Comment by ZenithCode** [comment]
Same issue on 2018.2.11f1. 

1. The package from Package Manager has issues with namespace` using UnityEngine.Rendering.PostProcessing;`

2. The latest package as is today throws this all the time:
`NullReferenceException: Object reference not set to an instance of an object
UnityEngine.Rendering.PostProcessing.AmbientOcclusion.IsEnabledAndSupported (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Assets/PostProcessing-2/PostProcessing/Runtime/Effects/AmbientOcclusion.cs:90)`

**Comment by cpetry** [comment]
I also got this error. Is there a (new) fix for this?

**Comment by demonixis** [comment]
Another way to reproduce this bug is to use `gameObject.AddComponent<PostProcessLayer>()` in a build.

**Comment by doukasd** [comment]
I was getting the same on latest Unity (2018.2 and 2018.3) and latest PostProcessing (2.1.2).

As is mentioned earlier, just remove and re-create the PostProcessing Layer, that resolved it for me.

**Comment by y4my4my4m** [comment]
@doukasd this fix doesn't work for me. Unless I'm doing it wrong, changing the layer, renaming, leaving it blank, doesn't seem to resolve it.. (2018.3)

**Comment by jeremedia** [comment]
Get the error every time when adding a PostProcessLayer component during runtime.

**Comment by y4my4my4m** [comment]
@jeremedia remove the "layer" script from your camera and re-add it. Fixed it for me.

**Comment by JulienAtWork** [comment]
Another workaround it to assign the PostProcessingResources at runtime via Init(resources), although this requires manually keeping a reference to the Resource asset (that can't even be browsed by the picker as it's under packages)

**Comment by sergiosolorzano** [comment]
Still a problem in 2019.2.2, same prefab update suggested above worked

**Comment by stonstad** [comment]
To confirm what others have said here, this is STILL an outstanding issue if you are instantiating PostProcessLayer via script.

**Comment by sunsided** [comment]
Same issue here, had the Post-process Layer brought in by a Prefab. Instead of removing and re-adding it, simply resetting the layer also worked.

**Comment by SplenectomY** [comment]
Can confirm this is still happening, specifically when a prefab with a post processing component is brought into a new project. The null reference appears after installing Post Processing

**Comment by AlexHolderDeveloper** [comment]
Yep, just hit this issue & the fixes mentioned above all still work at least. I'm on 2019.3.2f1.

**Comment by Ruuubickk** [comment]
Same here on 2018.4.17f1

**Comment by niallobrien** [comment]
Still encountering this issue when spawning a character camera via script.

**Comment by roboserg** [comment]
I am having the same exact issue in 2020 with Unity 2019.3.13 on Post Processing package 2.3.0
[](https://i.imgur.com/j8CoR6m.png)

`NullReferenceException: Object reference not set to an instance of an object
UnityEngine.Rendering.PostProcessing.AmbientOcclusion.IsEnabledAndSupported (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Library/PackageCache/com.unity.postprocessing@2.3.0/PostProcessing/Runtime/Effects/AmbientOcclusion.cs:182)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.SetLegacyCameraFlags (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Library/PackageCache/com.unity.postprocessing@2.3.0/PostProcessing/Runtime/PostProcessLayer.cs:771)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.SetupContext (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Library/PackageCache/com.unity.postprocessing@2.3.0/PostProcessing/Runtime/PostProcessLayer.cs:863)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.BuildCommandBuffers () (at Library/PackageCache/com.unity.postprocessing@2.3.0/PostProcessing/Runtime/PostProcessLayer.cs:533)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.OnPreCull () (at Library/PackageCache/com.unity.postprocessing@2.3.0/PostProcessing/Runtime/PostProcessLayer.cs:462)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)`

Any workaround or fix from Unity? I am on a builtIn rendering pipeline.

**Comment by roboserg** [comment]
Wait, why is this ticket closed, the issue is still there

**Comment by samavan** [comment]
Just imported the Post-Pocessing package.
Work fine the whole thing is premade on a camera.
But if you make a PostProcessingLayer + PostProcessingVolume then load & assign the Profile from the Resources, it will call back that same error from the AmbientOcclusion (which I am not using at all).
![image](https://user-images.githubusercontent.com/6184992/82980878-c26dfe80-a014-11ea-86d3-2001762da464.png)

**Comment by samavan** [comment]
Fix here : 
- https://forum.unity.com/threads/post-process-stack-nullrefferenceexception.647479/#post-5624242
