### ISSUE TITLE
[V2] Where to find compatible LUTs for color grading?

### ISSUE THREAD

**Issue by AubreyF** [Unity-Technologies/PostProcessing#507]
This is not a bug, this is a request for information. I've had a post on Unity Answers open for nearly a month now, and have also asked in several chat rooms and reached out to the developer of a LUT package on the Asset Store. So far, no one has answers. I'm posting here to reach the most knowledgeable devs on the V2 postfx stack.

It appears that the V2 stack is not backwards-compatible with V1 LUT images. Does anyone know if V1 LUTs can be converted to the V2 spec, or if all existing LUT packages need to be recreated from scratch?

Here is my Unity Answers post:
https://answers.unity.com/questions/1474417/where-to-find-postfx-v2-compatible-luts-for-color.html

**Comment by Chman** [comment]
The [documentation](https://github.com/Unity-Technologies/PostProcessing/wiki/Color-Grading) is currently incomplete for the Color Grading effect but you're using the wrong field to put your strip-LUT in (see the warning displayed underneath).

The "External" grading mode expects a log-encoded 3D texture, not a standard strip-LUT. I haven't had the time to cleanup the doc about this specific mode yet, but you'll find the [old pages here](https://github.com/Unity-Technologies/PostProcessing/wiki/(v2)-External-LUT-authoring).

If you want to use a LDR strip-LUT switch the Color Grading mode to "Low Definition Range". You'll be able to put your LUT there (you may have to flip it vertically though).

**Comment by AubreyF** [comment]
Hi Thomas! Thanks for the update. I just experimented with an asset store collection of LDR LUTs which work correctly in the PostFX V1 stack and in other third-party tools.

I put together a powershell script to batch-flip these images:

```
$path = "C:\Users\Aubrey\Projects\Terra\terra-unity3d\Assets\Plugins\Rendering\Cinematic LUT\LUTs" #target directory

[System.Reflection.Assembly]::LoadWithPartialName("System.Drawing")
Get-ChildItem -recurse ($path) -include @("*.png", "*.jpg") |

ForEach-Object {
  Write-Output "Processing Image:" + $_;
  $image = [System.Drawing.image]::FromFile( $_ )
  $image.rotateflip("RotateNoneFlipY")
  $image.save($_)
}
```

I tried flipping them horizontally, vertically, and both. Each of these combinations resulted in a non-working kaleidoscope when used with the V2 stack in LDR mode.

Here are the import settings I am using for these LUT images:

![lut_import_settings](https://user-images.githubusercontent.com/2789037/37981685-2ea646d0-31a3-11e8-824c-3b5eec9bc579.jpg)

Here is a test scene with no LUT applied:

![lut_disabled](https://user-images.githubusercontent.com/2789037/37981710-3e6b2c66-31a3-11e8-910a-9dd8de895dfd.jpg)

Here is the same scene with our test LDR LUT applied:

![lut_enabled](https://user-images.githubusercontent.com/2789037/37981729-4bc37d50-31a3-11e8-8fa7-6825d2f2f408.jpg)

What needs to happen to get these LUTs working properly?

Alternatively, are you aware of any collections of log-encoded 3D texture LUTs? I am fine paying for such a collection, but haven't been able to find any yet.

**Comment by Chman** [comment]
Indeed, there's a problem with small luts as everything is currently hardcoded to expect 32^3 (1024x32) luts. Thanks for raising this, I'll re-open the issue until I have a proper fix ready. Handling different lut sizes also have a few implications I need to look into (like blending between different sizes luts, that kind of things).

As for collections of log-encoded luts, this is a tough one. These are specific to Unity, the same way log luts in the movie industry are specific to camera models unless you go through a lut transform chain first. So right now I don't think anyone has made any (maybe we'll see packs on the asset store at some point in the near future). If anything, you should be able to grab "generic" CUBE luts and use them in Photoshop ([step 4 of this small guide](https://github.com/Unity-Technologies/PostProcessing/wiki/%28v2%29-Adobe-Photoshop)) to transform them to Unity log-luts.

Mind you, the log-lut workflow only applies if you're working in HDR and needs to color grade in HDR or if you're used to film grading. If you don't you can stick to the standard strip lut (only works for 1024x32 luts right now, I'm working on fixing this).

**Comment by AubreyF** [comment]
Thanks again! Your latest response addressed my remaining questions. I'm looking forward to the fix for non-1024 LDR LUT files. Ideally, any LDR LUT compatible with the V1 stack would also work in a similar fashion with the V2.

**Comment by Chman** [comment]
> Ideally, any LDR LUT compatible with the V1 stack would also work in a similar fashion with V2.

Indeed, this is an oversight, adding volume blending into the mix made this a bit more complicated than simply handling variable sizes. I fixed it locally but I need to fix a few other related things before I push it.

**Comment by Chman** [comment]
I pushed the 256x16 fix + improvements to the texture blending code. Let me know how it works for you.

**Comment by parodyband** [comment]
still doesn't work for me. I get this.  
![image](https://user-images.githubusercontent.com/1767779/39955136-fb8019fc-557e-11e8-82c2-ab70f8cb2cad.png)
