### ISSUE TITLE
Effects don't work in Scene View in 5.6.x

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#71]
Like antialiasing, bloom. The unity version is 5.6.0b3.

**Comment by Kink3d** [comment]
Hi,

Thanks for the report. We are aware of this issue in current 5.6 beta but dont have a way to safely apply a fix as of yet. We will let you know when it is resolved.

**Comment by cakeslice** [comment]
Hello, 5.6 is about to get released and I think this issue should be given top priority since previewing effects in the scene view is essential to work on the scene (the most important being tonemapping and color grading which don't work for me)

**Comment by Kink3d** [comment]
Hey all,

This fix is now in queue for a patch, It should make 5.6.0p2 but I will update here either way.

**Comment by OrtOfOn** [comment]
Hi Kink3d,

Is this an issue on the engine side? Do we need to wait for 5.6.0p2?

**Comment by Chman** [comment]
Yes, it's engine side. It should be fixed starting with 5.6.0p2.

**Comment by gvrocksnow** [comment]
I've upgraded to 5.6.0p2 but still have this issue. Am I missing something?

**Comment by Chman** [comment]
You're not missing anything. Like Matt & I said, it _should_ be fixed in 5.6.0p2 but it looks like the fix didn't make the cut for p2 (it's not on the changelog), I'd expect it to be in p3 then.

This issue will remain opened until the fix is publicly available.

**Comment by Kink3d** [comment]
Update: this branch missed patch 3 as well due to a failing graphics test. It will be in patch 4 on May 3rd (unless there is a disaster).

**Comment by OrtOfOn** [comment]
Hi guys. Can we expect the fixed bug today? It starts to become quite long for a such annoying bug :(

**Comment by McMayhem88** [comment]
So... I take it there was some sort of disaster then?

**Comment by OrtOfOn** [comment]
Guys? Anything on this? 
It is very difficult to work without this feature.

**Comment by Kink3d** [comment]
Hey,

The fix is in patch 4. Which was supposed to be released last Wednesday (03/05). I'll chase up the guys responsible for patch releases on Monday to see what happened...

**Comment by nonamejuju** [comment]
I can confirm that this issue is finally resolved with patch 4.
Thanks to everyone who worked on this.

**Comment by OrtOfOn** [comment]
Thanks you very much for this!

**Comment by McMayhem88** [comment]
I can also confirm it is working now in 5.6p4. Thank you Kink3d for staying on this issue and keeping us updated. I really appreciate that!
