### ISSUE TITLE
Depth of field changes depending on the resolution

### ISSUE THREAD

**Issue by SloMoShun** [Unity-Technologies/PostProcessing#780]
When using depth of field on post processing stack v2 it seems like it has different results depending on if I'm using 720p, 1080p and 4k. This seems like a pretty big oversight and makes it pretty useless since players would use all kinds of resolutions and change the look of the game.

Is there a fix for this? Im using Unity 2018.3.9f1 with PP 2.1.4

Thanks.

**Comment by FriedrichCoder** [comment]
https://github.com/Unity-Technologies/PostProcessing/issues/29

Will this be fixed in Unity 2019?

**Comment by SloMoShun** [comment]
I made that change, and while it did help a little, it didn't completely fix the problem. There are still big differences from going 720p, 1080p and 4k.

**Comment by NFMynster** [comment]
Bump! This is still an issue with 2019.1
